Modified cni-odl with new ip address allocation mechanism; added get-ip script referenced by the file
Change-Id: I9a9acc1058d241020e3728b00d0df5f57565f488
Signed-off-by: Rihab Banday <rihab.banday@ericsson.com>

diff --git a/resources/poc/cni.plugin/cni-odl b/resources/poc/cni.plugin/cni-odl
--- a/resources/poc/cni.plugin/cni-odl
+++ b/resources/poc/cni.plugin/cni-odl
@@ -6,13 +6,41 @@
 # terms of the Eclipse Public License v1.0 which accompanies this distribution,
 # and is available at http://www.eclipse.org/legal/epl-v10.html
 #
-# Authors : Rihab Banday, Faseela K
+# Authors : Volker Luessem, Rihab Banday, Faseela K
 
 #
 # sample k8s cni plugin for opendaylight
 #
+
 DIR=$(dirname $(readlink -f $0))
 source $DIR/configuration
+
+#
+# The function to exit the plugin in case of an error
+#
+function error
+{
+cat << EOF
+{
+  "cniVersion": "0.1.0",
+  "code": "100",
+  "msg": "$1"
+}
+EOF
+
+echo "+++ Plugin execution finished with error: $1 +++" >> $OUTFILE
+
+# Append temporary log to log
+cat $OUTFILE >> $LOGFILE
+rm $OUTFILE
+
+exit 1
+}
+
+
+#
+# The script starts here
+#
 
 # Make sure that directory /var/run/netns exists
 mkdir -p /var/run/netns
@@ -42,11 +70,14 @@ TENANT=$(grep -Po 'K8S_POD_NAMESPACE=\K[^ ]+' $ARGFILE | cut -d ';' -f 1) 2>> $O
 rm $ARGFILE
 
 # Fetch ELAN name for the tenant from etcd
-# Make sure that ssh to host running etcd is possible without password (ssh key)
-ELAN=`ssh root@{control-node-ip} "/opt/bin/etcdctl get /poc/tenants/$TENANT/elan"` 2>> $OUTFILE
+ELAN=$(/opt/bin/etcdctl --endpoints $ETCD get /poc/tenants/$TENANT/elan) &>> $OUTFILE
+if [ -z $ELAN ]
+then
+  error "Elan name empty"
+fi
 
 # Generate device names for the veth link
-VETH=veth$PID
+VETH=veth$DIFFERENTIATOR$PID
 VETHTMP=veth$PIDtmp
 
 if [ "$CNI_COMMAND" = "ADD" ]
@@ -56,11 +87,21 @@ then
 #
 
 # Generate an IP address for the new container
-IP=`cat $LAST_IP`
-if [ "$IP" = "254" ]; then IP=1; fi
-IP=$((IP+1))
-echo $IP > $LAST_IP
-IP_ADDR=$IP_PREFIX$IP/16
+IP_PREFIX=$(/opt/bin/etcdctl --endpoints $ETCD get /poc/tenants/$TENANT/subnet | cut -d. -f1,2) &>> $OUTFILE
+if [ -z $IP_PREFIX ]
+then
+  error "IP-Prefix empty"
+fi
+
+IP=$($DIR/get-ip /poc/tenants/$TENANT/ip $ETCD)
+if [ -z $IP ]
+then
+  error "IP empty"
+fi
+IP_LOW=$($DIR/get_low_byte $IP)
+IP_HIGH=$($DIR/get_high_byte $IP)
+
+IP_ADDR="$IP_PREFIX.$IP_HIGH.$IP_LOW/16"
 
 # Log generated information
 echo "tenant name for this container: $TENANT" >> $OUTFILE
@@ -68,8 +109,12 @@ echo "elan name for this container $ELAN" >> $OUTFILE
 echo "IP address for this container: $IP_ADDR" >> $OUTFILE
 echo "veth endpoint for this container: $VETH" >> $OUTFILE
 
+
 # Create a veth link using the veth endpoint and the temporary veth endpoint
 ip link add $VETH type veth peer name $VETHTMP 2>> $OUTFILE
+
+# Disable TCP checksum offload for container interface
+ethtool --offload $VETHTMP rx off tx off 2>> $OUTFILE >> /dev/null
 
 # Create a named network namspace
 ln -s /proc/$PID/ns/net /var/run/netns/$PID 2>> $OUTFILE
@@ -82,10 +127,11 @@ ip netns exec $PID ip link set name $CNI_IFNAME dev $VETHTMP
 
 # Add the other endpoint of the veth link to the OVS bridge and bring it up
 ip link set $VETH up 2>> $OUTFILE
-/opt/openvswitch/install/bin/ovs-vsctl add-port $BRIDGE $VETH 2>> $OUTFILE
+#/opt/openvswitch/install/bin/ovs-vsctl add-port $BRIDGE $VETH 2>> $OUTFILE
+/opt/css-3/install/bin/ovs-vsctl-3 add-port $BRIDGE $VETH 2>> $OUTFILE
 
 # Create the new port in the controller and connect it to the ELAN
-$DIR/configure_odl "ADD" $VETH $ELAN $OUTFILE 
+$DIR/configure_csc "ADD" $VETH $ELAN $OUTFILE
 
 # Assign an IP address to the interface in the container and bring it up
 ip netns exec $PID ip address add $IP_ADDR dev $CNI_IFNAME 2>> $OUTFILE
@@ -93,15 +139,18 @@ ip netns exec $PID ip link set dev $CNI_IFNAME up 2>> $OUTFILE
 
 # Add a default route in the container
 #ip netns exec $PID ip route add default via $BRIDGE_IP
+ip netns exec $PID ip route add default via 10.0.0.10
+#ip netns exec $PID ip route add 192.168.3.0/24 dev $CNI_IFNAME 2>> $OUTFILE
 
 else
 #
 # DEL command
 #
-/opt/openvswitch/install/bin/ovs-vsctl del-port $BRIDGE $VETH 2>> $OUTFILE
+#/opt/openvswitch/install/bin/ovs-vsctl del-port $BRIDGE $VETH 2>> $OUTFILE
+/opt/css-3/install/bin/ovs-vsctl-3 del-port $BRIDGE $VETH 2>> $OUTFILE
 ip link del $VETH type veth peer name $CNI_IFNAME 2>> $OUTFILE
 rm -r /var/run/netns/$PID
-$DIR/configure_odl "DEL" $VETH $ELAN $OUTFILE
+$DIR/configure_csc "DEL" $VETH $ELAN $OUTFILE
 fi
 
 cat << EOF
@@ -113,10 +162,9 @@ cat << EOF
 }
 EOF
 
-echo "+++ Plugin execution finished +++" >> $OUTFILE
-
 # Append temporary log to log
 cat $OUTFILE >> $LOGFILE
 rm $OUTFILE
 
 exit 0
+
